[toolchain]
channel = "1.70.0"
profile = "default"  # see https://rust-lang.github.io/rustup/concepts/profiles.html
components = ["rustfmt","rust-analyzer","clippy"]  # see https://rust-lang.github.io/rustup/concepts/components.html
